version: '3.1'

services:

  mongo:
    image: mongo:6
    container_name: mongo-mern
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: bookstore-mern